const products = [
    {
      id: 1,
      name: 'Nike Kid',
      description: 'A perfect product for kids',
      price: 100,
      ratings: 4,
      image: 'https://res.cloudinary.com/moresport/image/upload/a_0,c_fill,f_auto,q_auto:good/v1575961299/uploads/assets/1156338-BLACKBLACKWHITE-1-a4M.jpg', 
      category: 'Bags',
    },
    {
      id: 2,
      name: 'Nike Air Force',
      description: 'Good and comfortable sneakers for everyday use',
      price: 145,
      ratings: 4,
      image: 'https://lishop.store/image/cache/products/9/1/2/nike-air-force-1-white-black-1000x1000.jpg',
      category: 'Shoes',
    },
    {
      id: 3,
      name: 'Nike Air Max',
      description: 'A perfect choice for running and walking',
      price: 230,
      ratings: 5,
      image: 'https://i.ebayimg.com/images/g/DZMAAOSwX4Zjhsf7/s-l1600.jpg', 
      category: 'Shoes',
    },
    {
      id: 4,
      name: 'Under Armour',
      description: 'Good choice for exercising',
      price: 160,
      ratings: 5,
      image: 'https://www.tradeinn.com/f/13904/139042300/under-armour-lockdown-6-basketball-shoes.jpg', 
      category: 'Shoes',
    },
    {
      id: 5,
      name: 'PUMA',
      description: 'A good bag to carry your gym equipment',
      price: 45,
      ratings: 3,
      image: 'https://img.tatacliq.com/images/i7/437Wx649H/MP000000009094957_437Wx649H_202103162126281.jpeg', 
      category: 'Bags',
    },
    {
      id: 6,
      name: 'Trawoc 80 ltrs',
      description: 'The perfect bag for long hiking',
      price: 250,
      discountedPrice: 150,
      ratings: 5,
      image: 'https://m.media-amazon.com/images/I/81kiA9M+IoL._AC_UY1100_.jpg', 
      category: 'Bags',
    },
    {
      id: 7,
      name: 'Under Armour Undeniable Sport Bag',
      description: 'A good bag to carry your gym equipment',
      price: 180,
      discountedPrice: 165,
      ratings: 5,
      image: 'https://www.tradeinn.com/f/13907/139070669/under-armour-undeniable-5.0-144l-sport-bag.jpg', 
      category: 'Bags',
    },
    {
      id: 8,
      name: 'Puma Challenger Bag',
      description: 'Good to carry most of your clothes and stuff',
      price: 110,
      ratings: 3,
      image: 'https://i0.wp.com/brandzz.co.za/wp-content/uploads/2022/02/41826-Puma-Travel-Bags-Challenger-Black-Main.jpg?fit=679%2C670&ssl=1', 
      category: 'Bags',
    },
    {
      id: 9,
      name: 'Fila Sandblas',
      description: 'Affordable shoe and decent quality',
      price: 60,
      discountedPrice: 40,
      ratings: 3,
      image: 'https://www.vigliettisport.com/629376-large_default/shoe-fila-sandblast-l-woman.jpg', 
      category: 'Shoes',
    },
    {
      id: 10,
      name: 'Beach bag',
      description: 'The perfect choice for beach bag',
      price: 25,
      ratings: 3,
      image: 'https://cdn-images.farfetch-contents.com/19/90/44/47/19904447_44700738_600.jpg', 
      category: 'Bags',
    },
    
    {
      id: 11,
      name: 'Nike Heritage Drawstring Bag',
      description: 'A small bag to bring with  you water and some food',
      price: 35,
      ratings: 4,
      image: 'https://static.nike.com/a/images/t_default/a6505d0f-c6bc-418c-8fbf-1c4966468b13/heritage-drawstring-bag-qFB8TZ.png', 
      category: 'Bags',
    },
    
    {
      id: 12,
      name: 'Sneakers',
      description: 'Affordable shoe but poor quality',
      price: 30,
      ratings: 2,
      image: 'https://process.fs.grailed.com/AJdAgnqCST4iPtnUxiGtTz/auto_image/cache=expiry:max/rotate=deg:exif/output=quality:70/compress/QFXKw44PT0SkV04J9mke', 
      category: 'Shoes',
    },
    {
      id: 13,
      name: 'Air Jordan',
      description: 'The perfect shoe for an intense game of basketball',
      price: 300,
      discountedPrice: 275,
      ratings: 5,
      image: 'https://static.nike.com/a/images/t_default/df202e47-3b8f-4d70-9b95-d22218430a45/air-jordan-xxxvii-low-basketball-shoes-7x01GN.png', 
      category: 'Shoes',
    },
    {
      id: 14,
      name: 'DC Skate',
      description: 'Оne of the best skateboard shoe choices',
      price: 175,
      ratings: 4,
      image: 'https://www.dapperconfidential.com/wp-content/uploads/2018/07/Skate-Shoes-1-DC-Court-Graffik-e1566488553290.jpg.webp', 
      category: 'Shoes',
    },
    {
      id: 15,
      name: 'Addidas Slides',
      description: 'The perfect choice for daily use and running',
      price: 145,
      discountedPrice: 135,
      ratings: 4,
      image: 'https://i8.amplience.net/s/scvl/113069_306324_SET/1?fmt=auto&$webPlp$', 
      category: 'Shoes',
    },
    
    {
      id: 16,
      name: 'Addidas Sneaker',
      description: 'Good sneaker for daily use ',
      price: 100,
      ratings: 3,
      image: 'https://images.journeys.ca/images/products/1_581834_FS_ALT5.JPG', 
      category: 'Shoes',
    },
    {
      id: 17,
      name: 'Under Armour Sl Shoes',
      description: 'Оne of the best shoe choices for golf',
      price: 175,
      ratings: 5,
      image: 'https://www.foremostgolf.com/images/thumbs/0087340_under-armour-mens-charged-phantom-sl-golf-shoes.jpeg', 
      category: 'Shoes',
    },
    {
      id: 18,
      name: 'ADIDAS LINEAR CORE BACKPACK',
      description: 'A perfect choice for a school bag',
      price: 75,
      discountedPrice: 70,
      ratings: 4,
      image: 'https://i.ebayimg.com/images/g/ctcAAOSwQyBfAZ2R/s-l1200.webp', 
      category: 'Bags',
    },
    {
      id: 19,
      name: 'Adidas Essentials Training',
      description: 'The perfect bag for gym',
      price: 85,
      ratings: 5,
      image: 'https://sportscentral.ph/cdn/shop/files/HT4747_1_HARDWARE_Photography_FrontCenterView_greyBackgroundRemoved_1080x.jpg?v=1688449140', 
      category: 'Bags',
    },
    {
      id: 20,
      name: 'Under Armour Men Project Rock',
      description: 'A good bag for hiking',
      price: 90,
      discountedPrice: 80,
      ratings: 4,
      image: 'https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1537448952-1345663-040_SLF_SL.jpg?crop=1xw:1xh;center,top&resize=980:*', 
      category: 'Bags',
    },
    
    {
      id: 21,
      name: 'Under Armour',
      description: 'A good bag for everyday use',
      price: 70,
      ratings: 4,
      image: 'https://cdna.lystit.com/400/500/tr/photos/stand-out/925cdcc1/under-armour-Navy-Hustle-Lite-Backpack.jpeg', 
      category: 'Bags',
    },
    {
      id: 22,
      name: 'Under Armour',
      description: 'A good bag for everyday use',
      price: 80,
      discountedPrice: 45,
      ratings: 4,
      image: 'https://classic.cdn.media.amplience.net/i/hibbett/1746C_0256_main?w=300&h=300&img404=404&v=1', 
      category: 'Bags',
    },
    
  
  ];

  export default products