const products = [
    {
      id: 1,
      name: 'Nike Kid',
      description: 'A perfect product for kids',
      price: 100,
      ratings: 4,
      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/d97878a3-5935-48f0-be47-febeb81a3af6/backpack-L2kfrZ.png', 
      category: 'Bags',
    },
    {
      id: 2,
      name: 'Nike Air Force',
      description: 'This is the description of Product 2.',
      price: 145,
      ratings: 4,
      image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes-rWtqPn.png',
      category: 'Shoes',
    },
    {
      id: 3,
      name: 'Nike Air Max',
      description: 'A Perfect choice shoe for running and walking',
      price: 230,
      ratings: 5,
      image: 'https://sizeer.bg/media/cache/gallery/rc/0to83lyy/nike-air-max-270-mazhki-maratonki-cheren-ah8050-002.jpg', 
      category: 'Shoes',
    },
    {
      id: 4,
      name: 'Under Armour',
      description: 'Good choice for exercising',
      price: 160,
      ratings: 5,
      image: 'https://s13emagst.akamaized.net/products/47913/47912519/images/res_ee39c13cf7fac80817b463c61cf9d933.jpg', 
      category: 'Shoes',
    },
    {
      id: 5,
      name: 'Under armour Hustle Sport',
      description: 'A good bag to carry your gym equipment',
      price: 165,
      ratings: 4,
      image: 'https://www.sportihobi.bg/sites/default/files/styles/uc_product_full/public/638811692/under-armour-hustle-sport-backpack-backpacks.jpg?itok=AW_cGn7m', 
      category: 'Bags',
    },
    {
      id: 6,
      name: 'Trawoc 80 ltrs',
      description: 'The perfect bag for long hiking',
      price: 250,
      ratings: 5,
      image: 'https://m.media-amazon.com/images/I/81kiA9M+IoL._AC_UY1100_.jpg', 
      category: 'Bags',
    },
    {
      id: 7,
      name: 'Under Armour Undeniable 5.0 144L Sport Bag',
      description: 'A good bag to carry your gym equipment',
      price: 180,
      ratings: 5,
      image: 'https://www.tradeinn.com/f/13907/139070669/under-armour-undeniable-5.0-144l-sport-bag.jpg', 
      category: 'Bags',
    },
    {
      id: 8,
      name: 'Puma Challenger Bag',
      description: 'Good to carry most of your clothes and stuff',
      price: 110,
      ratings: 3,
      image: 'https://i0.wp.com/brandzz.co.za/wp-content/uploads/2022/02/41826-Puma-Travel-Bags-Challenger-Black-Main.jpg?fit=679%2C670&ssl=1', 
      category: 'Bags',
    },
    {
      id: 9,
      name: 'PULL&BEAR',
      description: 'Affordable shoe but poor quality and uncomfortable experience',
      price: 35,
      ratings: 2,
      image: 'https://static.pullandbear.net/2/photos/2023/I/1/2/p/2218/140/001/2218140001_1_1_3.jpg?t=1690959603635', 
      category: 'Shoes',
    }
    
  ];

  export default products